# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow3.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication,QMainWindow
import sys

class Ui_Form(QMainWindow):

    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.retranslateUi(self)

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1600, 900)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(-1, 0, 1602, 901))
        self.frame.setStyleSheet("QFrame#frame{\n"
"background-image: url(:/picture/backgroud2.jpg);\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(450, 100, 450, 100)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMinimumSize(QtCore.QSize(140, 60))
        self.frame_2.setStyleSheet("QFrame{\n"
"background-color:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 rgb(184, 222, 255,0.3),stop:1 rgb(227, 255, 225,0.3));\n"
"border-radius:20px\n"
"}")
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(20, 40, 20, 20)
        self.verticalLayout_2.setSpacing(50)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setMinimumSize(QtCore.QSize(140, 100))
        self.label.setStyleSheet("font: 22pt \"宋体\";\n"
"background-color:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 rgb(184, 222, 255),stop:1 rgb(227, 255, 225));\n"
"border-radius:20px")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.widget = QtWidgets.QWidget(self.frame_2)
        self.widget.setMinimumSize(QtCore.QSize(140, 240))
        self.widget.setStyleSheet("background-color:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 rgb(184, 222, 255,0.7),stop:1 rgb(227, 255, 225,0.7));\n"
"border-radius:20px")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setMinimumSize(QtCore.QSize(140, 60))
        self.pushButton.setStyleSheet("QPushButton{\n"
"font: 20pt \"宋体\";\n"
"background-color:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 rgb(184, 222, 255),stop:1 rgb(227, 255, 225));\n"
"border-radius:20px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 rgb(224, 229, 255),stop:1 rgb(244, 255, 229));\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 rgb(120, 128, 159),stop:1 rgb(132, 148, 128));\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(140, 60))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"font: 20pt \"宋体\";\n"
"background-color:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 rgb(184, 222, 255),stop:1 rgb(227, 255, 225));\n"
"border-radius:20px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 rgb(224, 229, 255),stop:1 rgb(244, 255, 229));\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 rgb(120, 128, 159),stop:1 rgb(132, 148, 128));\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setMinimumSize(QtCore.QSize(140, 60))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"font: 20pt \"宋体\";\n"
"background-color:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 rgb(184, 222, 255),stop:1 rgb(227, 255, 225));\n"
"border-radius:20px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 rgb(224, 229, 255),stop:1 rgb(244, 255, 229));\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 rgb(120, 128, 159),stop:1 rgb(132, 148, 128));\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.verticalLayout_2.addWidget(self.widget)
        self.horizontalLayout.addWidget(self.frame_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "智能风机缺陷检测运维平台V2.0"))
        self.label.setText(_translate("Form", "智能风机缺陷检测运维平台V2.0"))
        self.pushButton.setText(_translate("Form", "图片识别"))
        self.pushButton_2.setText(_translate("Form", "视频识别"))
        self.pushButton_3.setText(_translate("Form", "数据图表分析"))

import main_rc

if __name__ == '__main__':
    app = QApplication(sys.argv)
    MainWindow1 = QMainWindow()     #MainWindow1随便改
    ui = Ui_Form()             #随便改
    ui.setupUi(MainWindow1)
    MainWindow1.show()
    sys.exit(app.exec_())
